### ISSUE TITLE
Error when searching for UglifyJS and UglifyCSS binaries

### ISSUE THREAD

**Issue by Pierstoval** [symfony/AsseticBundle#369]
It's been a long time since I had this bug in prod (debian7) and on my MacOS, and could never find how to solve it, because it works on my Windows environment (and actually the OS does not seem to matter, or I don't know how it works...).
 
When you install UglifyJS and UglifyCSS **locally** (I mean in `%kernel.root_dir%/../node_modules`) and want to use them, dumping the assets with assetic will not work for these two libraries.
 
Actually, after some debugging, I found that the `UglifyJsFilter` class (as well as `UglifyCssFilter`) are not constructed with the correct binary value.

We'll take the example for `UglifyJS` only, because it's almost the same for `UglifyCSS`.
 
The default value for the `$uglifyjsBin` is `/usr/bin/uglifyjs`.
When I set this on my assetic config:

```yml
assetic:
        uglifyjs:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
```

The `node_paths` is never used, and I have big error:

```
  [Assetic\Exception\FilterException]
  An error occurred while running:
  '/usr/local/bin/node' '/usr/bin/uglifyjs' '--no-mangle' '-o' '/private/var/folders/5m/q3lzl3_523db19syzdt5dp3wpkwfgy/T/outputtnnslf' '/private/var/folders/5m/q3lzl3_523db19syzdt5dp3wpkwfgy/T/inputZAkrYE'
  Error Output:
  module.js:338
      throw err;
            ^
  Error: Cannot find module '/usr/bin/uglifyjs'
      at Function.Module._resolveFilename (module.js:336:15)
      at Function.Module._load (module.js:278:25)
      at Function.Module.runMain (module.js:501:10)
      at startup (node.js:129:16)
      at node.js:814:3
```

As said, uglifyjs is **not installed globally**, and the uglifyjs binary is located in `{project_dir}/node_modules/uglify-js/bin/uglifyjs`.

To solve this issue for both UglifyJS and UglifyCSS, I had to add this to my configuration:

```yml
# app/config/config.yml
parameters:
    assetic.filter.uglifyjs.bin: %node_modules_path%/uglify-js/bin/uglifyjs
    assetic.filter.uglifycss.bin: %node_modules_path%/uglifycss/uglifycss
```

I could not find any documentation about this, so it could be cool to first fix this when instantiating these filter classes, but I don't know how it's done in the bundle (seems too complex for me sorry for that :disappointed: ).

**Note:** Also, the UglifyJS filter does not work with UglifyJS 2.4+ and I had to force `2.3.*` version in my `package.json` file.

**Comment by Ninir** [comment]
Hey @Pierstoval,

this is the configuration I have at the moment, which is working pretty well:

```yaml

assetic:
    ...
    node: %node_bin_path%
    node_paths: %node_lib_paths%
    filters:
        uglifyjs2:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
```

Where `node_bin_path` is the absolute path to node, and `node_lib_paths` the absolute path to globally installed libs.
All of my binaries are installed in the project using npm, hence the paths you're seeing ;-)
(Using `"uglifycss": "0.0.15"` and `"uglify-js": "2.4.21"` as packages)

Hope it helps!

**Comment by Pierstoval** [comment]
That's what I use too (see the last comment of my last comment), but not directly under the `assetic` extension. I put the parameters under `parameters` because that's the exact "path" I saw when debugging the Assetic extensions for uglifyJS and uglifyCSS.
 
It's worth noting that it also works under the extension, it can save some space and remove confusion in the parameters :+1: 

What's pretty sad is that I could not find any documentation about the almost-mandatory `bin` parameters for these filters :confused: 
Every "guide" I found on the web was mostly about specifying the absolute path for `node` binary and the absolute path for `node_modules`, which (for better versionning capabilities) should be directly in the app (and not "global", to avoid permission issues or global installation conflicts risk)

**Comment by Ninir** [comment]
What you have IS the way to go; having them per project is the best idea :-)

If you want to find information about the filter, just check the [sources](https://github.com/kriswallsmith/assetic/tree/master/src/Assetic/Filter)... best way to go :/

Then, you can see the options that can be potentially used...

**Comment by Pierstoval** [comment]
That's what I've done to find the solution to my problem, but actually, without spending long minutes (or hours for the newcomers), I wouldn't have found it, and it's quite a problem.
 
Even though users start using things like Gulp or Grunt to optimize assets, a lot continue to use assetic (and I do, I have tons of assets in an old project, and it's hard work to migrate to Gulp even if I'd like to).
The problem is, dumping the assets with these two filters is a problem, and the documentation isn't helpful enough when it comes to what have to be done for the filters to work.

**Comment by Ninir** [comment]
Yup. It's a hard work to document every filter, how to use them, etc... but it would be worth it to do it, in order for Assetic to keep being on track :/

The minimum IMO would be to add something like "If you want to find information about a specific filter, check the sources. Here are the existing filters : [LIST]".
